version: '3.3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local-db:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3001"
    depends_on:
      - db

volumes:
  local-db: